package com.odtheking.odin.features.impl.dungeon.puzzlesolvers

import com.google.gson.GsonBuilder
import net.minecraft.util.math.BlockPos

object IceFillFloors {
    val IceFillFloors = arrayOf(
        arrayOf(
            arrayOf(
                BlockPos(0, 0, 0),
                BlockPos(0, 0, -1),
                BlockPos(1, 0, -1),
                BlockPos(1, 0, 0),
                BlockPos(1, 0, 1),
                BlockPos(2, 0, 1),
                BlockPos(2, 0, 0),
                BlockPos(3, 0, 0)
            ),
            arrayOf(
                BlockPos(0, 0, 0),
                BlockPos(0, 0, 1),
                BlockPos(1, 0, 1),
                BlockPos(1, 0, 0),
                BlockPos(1, 0, -1),
                BlockPos(2, 0, -1),
                BlockPos(2, 0, 0),
                BlockPos(3, 0, 0)
            ),
            arrayOf(
                BlockPos(0, 0, 0),
                BlockPos(1, 0, 0),
                BlockPos(1, 0, 1),
                BlockPos(2, 0, 1),
                BlockPos(2, 0, 0),
                BlockPos(3, 0, 0)
            ),
            arrayOf(
                BlockPos(0, 0, 0),
                BlockPos(1, 0, 0),
                BlockPos(1, 0, -1),
                BlockPos(2, 0, -1),
                BlockPos(2, 0, 0),
                BlockPos(3, 0, 0)
            )
        ),
        arrayOf(
            arrayOf(
                BlockPos(0, 0, 0),
                BlockPos(0, 0, -1),
                BlockPos(0, 0, -2),
                BlockPos(1, 0, -2),
                BlockPos(2, 0, -2),
                BlockPos(3, 0, -2),
                BlockPos(3, 0, -1),
                BlockPos(2, 0, -1),
                BlockPos(2, 0, 0),
                BlockPos(1, 0, 0),
                BlockPos(1, 0, 1),
                BlockPos(0, 0, 1),
                BlockPos(0, 0, 2),
                BlockPos(1, 0, 2),
                BlockPos(2, 0, 2),
                BlockPos(3, 0, 2),
                BlockPos(4, 0, 2),
                BlockPos(4, 0, 1),
                BlockPos(3, 0, 1),
                BlockPos(3, 0, 0),
                BlockPos(4, 0, 0),
                BlockPos(5, 0, 0)
            ),
            arrayOf(
                BlockPos(0, 0, 0),
                BlockPos(1, 0, 0),
                BlockPos(1, 0, -1),
                BlockPos(0, 0, -1),
                BlockPos(0, 0, -2),
                BlockPos(1, 0, -2),
                BlockPos(2, 0, -2),
                BlockPos(3, 0, -2),
                BlockPos(4, 0, -2),
                BlockPos(4, 0, -1),
                BlockPos(3, 0, -1),
                BlockPos(3, 0, 0),
                BlockPos(3, 0, 1),
                BlockPos(2, 0, 1),
                BlockPos(1, 0, 1),
                BlockPos(0, 0, 1),
                BlockPos(0, 0, 2),
                BlockPos(1, 0, 2),
                BlockPos(2, 0, 2),
                BlockPos(3, 0, 2),
                BlockPos(4, 0, 2),
                BlockPos(4, 0, 1),
                BlockPos(4, 0, 0),
                BlockPos(5, 0, 0),
            ),
            arrayOf(
                BlockPos(0, 0, 0),
                BlockPos(0, 0, -1),
                BlockPos(0, 0, -2),
                BlockPos(1, 0, -2),
                BlockPos(2, 0, -2),
                BlockPos(3, 0, -2),
                BlockPos(4, 0, -2),
                BlockPos(4, 0, -1),
                BlockPos(3, 0, -1),
                BlockPos(2, 0, -1),
                BlockPos(2, 0, 0),
                BlockPos(2, 0, 1),
                BlockPos(1, 0, 1),
                BlockPos(0, 0, 1),
                BlockPos(0, 0, 2),
                BlockPos(1, 0, 2),
                BlockPos(2, 0, 2),
                BlockPos(3, 0, 2),
                BlockPos(4, 0, 2),
                BlockPos(4, 0, 1),
                BlockPos(4, 0, 0),
                BlockPos(5, 0, 0),
            ),
            arrayOf(
                BlockPos(0, 0, 0),
                BlockPos(0, 0, -1),
                BlockPos(0, 0, -2),
                BlockPos(1, 0, -2),
                BlockPos(1, 0, -1),
                BlockPos(2, 0, -1),
                BlockPos(2, 0, -2),
                BlockPos(3, 0, -2),
                BlockPos(4, 0, -2),
                BlockPos(4, 0, -1),
                BlockPos(3, 0, -1),
                BlockPos(3, 0, 0),
                BlockPos(2, 0, 0),
                BlockPos(2, 0, 1),
                BlockPos(1, 0, 1),
                BlockPos(0, 0, 1),
                BlockPos(0, 0, 2),
                BlockPos(1, 0, 2),
                BlockPos(2, 0, 2),
                BlockPos(3, 0, 2),
                BlockPos(4, 0, 2),
                BlockPos(4, 0, 1),
                BlockPos(4, 0, 0),
                BlockPos(5, 0, 0),
            ),
            arrayOf(
                BlockPos(0, 0, 0),
                BlockPos(0, 0, -1),
                BlockPos(1, 0, -1),
                BlockPos(1, 0, -2),
                BlockPos(2, 0, -2),
                BlockPos(2, 0, -1),
                BlockPos(3, 0, -1),
                BlockPos(3, 0, 0),
                BlockPos(2, 0, 0),
                BlockPos(2, 0, 1),
                BlockPos(1, 0, 1),
                BlockPos(0, 0, 1),
                BlockPos(0, 0, 2),
                BlockPos(1, 0, 2),
                BlockPos(2, 0, 2),
                BlockPos(3, 0, 2),
                BlockPos(4, 0, 2),
                BlockPos(4, 0, 1),
                BlockPos(4, 0, 0),
                BlockPos(5, 0, 0),
            ),
            arrayOf(
                BlockPos(0, 0, 0),
                BlockPos(1, 0, 0),
                BlockPos(1, 0, 1),
                BlockPos(0, 0, 1),
                BlockPos(0, 0, 2),
                BlockPos(1, 0, 2),
                BlockPos(2, 0, 2),
                BlockPos(3, 0, 2),
                BlockPos(4, 0, 2),
                BlockPos(4, 0, 1),
                BlockPos(3, 0, 1),
                BlockPos(3, 0, 0),
                BlockPos(3, 0, -1),
                BlockPos(2, 0, -1),
                BlockPos(1, 0, -1),
                BlockPos(0, 0, -1),
                BlockPos(0, 0, -2),
                BlockPos(1, 0, -2),
                BlockPos(2, 0, -2),
                BlockPos(3, 0, -2),
                BlockPos(4, 0, -2),
                BlockPos(4, 0, -1),
                BlockPos(4, 0, 0),
                BlockPos(5, 0, 0),
            )
        ),
        arrayOf(
            arrayOf(
                BlockPos(0, 0, 0),
                BlockPos(1, 0, 0),
                BlockPos(2, 0, 0),
                BlockPos(3, 0, 0),
                BlockPos(3, 0, -1),
                BlockPos(2, 0, -1),
                BlockPos(1, 0, -1),
                BlockPos(0, 0, -1),
                BlockPos(0, 0, -2),
                BlockPos(1, 0, -2),
                BlockPos(1, 0, -3),
                BlockPos(2, 0, -3),
                BlockPos(2, 0, -2),
                BlockPos(3, 0, -2),
                BlockPos(3, 0, -3),
                BlockPos(4, 0, -3),
                BlockPos(5, 0, -3),
                BlockPos(6, 0, -3),
                BlockPos(6, 0, -2),
                BlockPos(5, 0, -2),
                BlockPos(4, 0, -2),
                BlockPos(4, 0, -1),
                BlockPos(5, 0, -1),
                BlockPos(5, 0, 0),
                BlockPos(5, 0, 1),
                BlockPos(5, 0, 2),
                BlockPos(4, 0, 2),
                BlockPos(3, 0, 2),
                BlockPos(3, 0, 1),
                BlockPos(2, 0, 1),
                BlockPos(1, 0, 1),
                BlockPos(0, 0, 1),
                BlockPos(0, 0, 2),
                BlockPos(0, 0, 3),
                BlockPos(1, 0, 3),
                BlockPos(1, 0, 2),
                BlockPos(2, 0, 2),
                BlockPos(2, 0, 3),
                BlockPos(3, 0, 3),
                BlockPos(4, 0, 3),
                BlockPos(5, 0, 3),
                BlockPos(6, 0, 3),
                BlockPos(6, 0, 2),
                BlockPos(6, 0, 1),
                BlockPos(6, 0, 0),
                BlockPos(7, 0, 0),
            ),
            arrayOf(
                BlockPos(0, 0, 0),
                BlockPos(1, 0, 0),
                BlockPos(1, 0, -1),
                BlockPos(0, 0, -1),
                BlockPos(0, 0, -2),
                BlockPos(0, 0, -3),
                BlockPos(1, 0, -3),
                BlockPos(1, 0, -2),
                BlockPos(2, 0, -2),
                BlockPos(2, 0, -3),
                BlockPos(3, 0, -3),
                BlockPos(4, 0, -3),
                BlockPos(5, 0, -3),
                BlockPos(6, 0, -3),
                BlockPos(6, 0, -2),
                BlockPos(5, 0, -2),
                BlockPos(4, 0, -2),
                BlockPos(3, 0, -2),
                BlockPos(3, 0, -1),
                BlockPos(4, 0, -1),
                BlockPos(4, 0, 0),
                BlockPos(3, 0, 0),
                BlockPos(3, 0, 1),
                BlockPos(4, 0, 1),
                BlockPos(4, 0, 2),
                BlockPos(3, 0, 2),
                BlockPos(2, 0, 2),
                BlockPos(1, 0, 2),
                BlockPos(1, 0, 1),
                BlockPos(0, 0, 1),
                BlockPos(0, 0, 2),
                BlockPos(0, 0, 3),
                BlockPos(1, 0, 3),
                BlockPos(2, 0, 3),
                BlockPos(3, 0, 3),
                BlockPos(4, 0, 3),
                BlockPos(5, 0, 3),
                BlockPos(6, 0, 3),
                BlockPos(6, 0, 2),
                BlockPos(5, 0, 2),
                BlockPos(5, 0, 1),
                BlockPos(5, 0, 0),
                BlockPos(6, 0, 0),
                BlockPos(7, 0, 0),
            ),
            arrayOf(
                BlockPos(0, 0, 0),
                BlockPos(0, 0, 1),
                BlockPos(1, 0, 1),
                BlockPos(1, 0, 2),
                BlockPos(0, 0, 2),
                BlockPos(0, 0, 3),
                BlockPos(1, 0, 3),
                BlockPos(2, 0, 3),
                BlockPos(3, 0, 3),
                BlockPos(4, 0, 3),
                BlockPos(5, 0, 3),
                BlockPos(5, 0, 2),
                BlockPos(6, 0, 2),
                BlockPos(6, 0, 1),
                BlockPos(5, 0, 1),
                BlockPos(4, 0, 1),
                BlockPos(4, 0, 2),
                BlockPos(3, 0, 2),
                BlockPos(3, 0, 1),
                BlockPos(3, 0, 0),
                BlockPos(2, 0, 0),
                BlockPos(2, 0, -1),
                BlockPos(1, 0, -1),
                BlockPos(0, 0, -1),
                BlockPos(0, 0, -2),
                BlockPos(0, 0, -3),
                BlockPos(1, 0, -3),
                BlockPos(1, 0, -2),
                BlockPos(2, 0, -2),
                BlockPos(2, 0, -3),
                BlockPos(3, 0, -3),
                BlockPos(4, 0, -3),
                BlockPos(5, 0, -3),
                BlockPos(6, 0, -3),
                BlockPos(6, 0, -2),
                BlockPos(5, 0, -2),
                BlockPos(4, 0, -2),
                BlockPos(3, 0, -2),
                BlockPos(3, 0, -1),
                BlockPos(4, 0, -1),
                BlockPos(5, 0, -1),
                BlockPos(5, 0, 0),
                BlockPos(6, 0, 0),
                BlockPos(7, 0, 0),
            ),
            arrayOf(
                BlockPos(0, 0, 0),
                BlockPos(1, 0, 0),
                BlockPos(1, 0, -1),
                BlockPos(0, 0, -1),
                BlockPos(0, 0, -2),
                BlockPos(0, 0, -3),
                BlockPos(1, 0, -3),
                BlockPos(1, 0, -2),
                BlockPos(2, 0, -2),
                BlockPos(2, 0, -3),
                BlockPos(3, 0, -3),
                BlockPos(4, 0, -3),
                BlockPos(5, 0, -3),
                BlockPos(6, 0, -3),
                BlockPos(6, 0, -2),
                BlockPos(5, 0, -2),
                BlockPos(4, 0, -2),
                BlockPos(4, 0, -1),
                BlockPos(5, 0, -1),
                BlockPos(5, 0, 0),
                BlockPos(4, 0, 0),
                BlockPos(3, 0, 0),
                BlockPos(2, 0, 0),
                BlockPos(2, 0, 1),
                BlockPos(3, 0, 1),
                BlockPos(4, 0, 1),
                BlockPos(4, 0, 2),
                BlockPos(3, 0, 2),
                BlockPos(2, 0, 2),
                BlockPos(1, 0, 2),
                BlockPos(0, 0, 2),
                BlockPos(0, 0, 3),
                BlockPos(1, 0, 3),
                BlockPos(2, 0, 3),
                BlockPos(3, 0, 3),
                BlockPos(4, 0, 3),
                BlockPos(5, 0, 3),
                BlockPos(6, 0, 3),
                BlockPos(6, 0, 2),
                BlockPos(6, 0, 1),
                BlockPos(6, 0, 0),
                BlockPos(7, 0, 0),
            ),
            arrayOf(
                BlockPos(0, 0, 0),
                BlockPos(0, 0, -1),
                BlockPos(1, 0, -1),
                BlockPos(2, 0, -1),
                BlockPos(2, 0, -2),
                BlockPos(1, 0, -2),
                BlockPos(0, 0, -2),
                BlockPos(0, 0, -3),
                BlockPos(1, 0, -3),
                BlockPos(2, 0, -3),
                BlockPos(3, 0, -3),
                BlockPos(4, 0, -3),
                BlockPos(5, 0, -3),
                BlockPos(6, 0, -3),
                BlockPos(6, 0, -2),
                BlockPos(5, 0, -2),
                BlockPos(4, 0, -2),
                BlockPos(4, 0, -1),
                BlockPos(5, 0, -1),
                BlockPos(5, 0, 0),
                BlockPos(5, 0, 1),
                BlockPos(4, 0, 1),
                BlockPos(4, 0, 2),
                BlockPos(3, 0, 2),
                BlockPos(2, 0, 2),
                BlockPos(2, 0, 1),
                BlockPos(1, 0, 1),
                BlockPos(0, 0, 1),
                BlockPos(0, 0, 2),
                BlockPos(0, 0, 3),
                BlockPos(1, 0, 3),
                BlockPos(2, 0, 3),
                BlockPos(3, 0, 3),
                BlockPos(4, 0, 3),
                BlockPos(5, 0, 3),
                BlockPos(5, 0, 2),
                BlockPos(6, 0, 2),
                BlockPos(6, 0, 1),
                BlockPos(6, 0, 0),
                BlockPos(7, 0, 0),
            )
        )
    )

    val advanced =
        arrayOf(
            arrayOf(
                arrayOf(
                    BlockPos(0, 0, 0),
                    BlockPos(0, 0, -1),
                    BlockPos(1, 0, -1),
                    BlockPos(1, 0, 0),
                    BlockPos(1, 0, 1),
                    BlockPos(2, 0, 1),
                    BlockPos(2, 0, 0),
                    BlockPos(3, 0, 0)
                ),
                arrayOf(
                    BlockPos(0, 0, 0),
                    BlockPos(0, 0, 1),
                    BlockPos(1, 0, 1),
                    BlockPos(1, 0, 0),
                    BlockPos(1, 0, -1),
                    BlockPos(2, 0, -1),
                    BlockPos(2, 0, 0),
                    BlockPos(3, 0, 0)
                ),
                arrayOf(
                    BlockPos(0, 0, 0),
                    BlockPos(1, 0, 0),
                    BlockPos(1, 0, 1),
                    BlockPos(2, 0, 1),
                    BlockPos(2, 0, 0),
                    BlockPos(3, 0, 0)
                ),
                arrayOf(
                    BlockPos(0, 0, 0),
                    BlockPos(1, 0, 0),
                    BlockPos(1, 0, -1),
                    BlockPos(2, 0, -1),
                    BlockPos(2, 0, 0),
                    BlockPos(3, 0, 0)
                )
            ),
            arrayOf(
                arrayOf(
                    BlockPos(0, 0, 0),
                    BlockPos(0, 0, -1),
                    BlockPos(0, 0, -2),
                    BlockPos(1, 0, -2),
                    BlockPos(2, 0, -2),
                    BlockPos(3, 0, -2),
                    BlockPos(3, 0, -1),
                    BlockPos(2, 0, -1),
                    BlockPos(2, 0, 0),
                    BlockPos(1, 0, 0),
                    BlockPos(1, 0, 1),
                    BlockPos(0, 0, 1),
                    BlockPos(0, 0, 2),
                    BlockPos(1, 0, 2),
                    BlockPos(2, 0, 2),
                    BlockPos(3, 0, 2),
                    BlockPos(4, 0, 2),
                    BlockPos(4, 0, 1),
                    BlockPos(3, 0, 1),
                    BlockPos(3, 0, 0),
                    BlockPos(4, 0, 0),
                    BlockPos(5, 0, 0)
                ),
                arrayOf(
                    BlockPos(-1, 0, 0),
                    BlockPos(-1, 1, 0),
                    BlockPos(-1, 1, 2),
                    BlockPos(0, 1, 2),
                    BlockPos(0, 0, 2),
                    BlockPos(1, 0, 2),
                    BlockPos(2, 0, 2),
                    BlockPos(3, 0, 2),
                    BlockPos(4, 0, 2),
                    BlockPos(4, 0, 1),
                    BlockPos(3, 0, 1),
                    BlockPos(2, 0, 1),
                    BlockPos(1, 0, 1),
                    BlockPos(0, 0, 1),
                    BlockPos(0, 0, 0),
                    BlockPos(1, 0, 0),
                    BlockPos(1, 0, -1),
                    BlockPos(0, 0, -1),
                    BlockPos(0, 0, -2),
                    BlockPos(1, 0, -2),
                    BlockPos(2, 0, -2),
                    BlockPos(3, 0, -2),
                    BlockPos(4, 0, -2),
                    BlockPos(4, 0, -1),
                    BlockPos(3, 0, -1),
                    BlockPos(3, 0, 0),
                    BlockPos(4, 0, 0),
                    BlockPos(5, 0, 0),
                ),
                arrayOf(
                    BlockPos(0, 0, 0),
                    BlockPos(0, 0, -1),
                    BlockPos(0, 0, -2),
                    BlockPos(1, 0, -2),
                    BlockPos(2, 0, -2),
                    BlockPos(3, 0, -2),
                    BlockPos(4, 0, -2),
                    BlockPos(4, 0, -1),
                    BlockPos(3, 0, -1),
                    BlockPos(2, 0, -1),
                    BlockPos(2, 0, 0),
                    BlockPos(2, 0, 1),
                    BlockPos(1, 0, 1),
                    BlockPos(0, 0, 1),
                    BlockPos(0, 0, 2),
                    BlockPos(1, 0, 2),
                    BlockPos(2, 0, 2),
                    BlockPos(3, 0, 2),
                    BlockPos(4, 0, 2),
                    BlockPos(4, 0, 1),
                    BlockPos(4, 0, 0),
                    BlockPos(5, 0, 0),
                ),
                arrayOf(
                    BlockPos(0, 0, 0),
                    BlockPos(0, 0, -1),
                    BlockPos(0, 0, -2),
                    BlockPos(1, 0, -2),
                    BlockPos(1, 0, -1),
                    BlockPos(2, 0, -1),
                    BlockPos(2, 0, -2),
                    BlockPos(3, 0, -2),
                    BlockPos(4, 0, -2),
                    BlockPos(4, 0, -1),
                    BlockPos(3, 0, -1),
                    BlockPos(3, 0, 0),
                    BlockPos(2, 0, 0),
                    BlockPos(2, 0, 1),
                    BlockPos(1, 0, 1),
                    BlockPos(0, 0, 1),
                    BlockPos(0, 0, 2),
                    BlockPos(1, 0, 2),
                    BlockPos(2, 0, 2),
                    BlockPos(3, 0, 2),
                    BlockPos(4, 0, 2),
                    BlockPos(4, 0, 1),
                    BlockPos(4, 0, 0),
                    BlockPos(5, 0, 0),
                ),
                arrayOf(
                    BlockPos(0, 0, 0),
                    BlockPos(0, 0, -1),
                    BlockPos(1, 0, -1),
                    BlockPos(1, 0, -2),
                    BlockPos(2, 0, -2),
                    BlockPos(2, 0, -1),
                    BlockPos(3, 0, -1),
                    BlockPos(3, 0, 0),
                    BlockPos(2, 0, 0),
                    BlockPos(2, 0, 1),
                    BlockPos(1, 0, 1),
                    BlockPos(0, 0, 1),
                    BlockPos(0, 0, 2),
                    BlockPos(1, 0, 2),
                    BlockPos(2, 0, 2),
                    BlockPos(3, 0, 2),
                    BlockPos(4, 0, 2),
                    BlockPos(4, 0, 1),
                    BlockPos(4, 0, 0),
                    BlockPos(5, 0, 0),
                ),
                arrayOf(
                    BlockPos(-1, 0, 0),
                    BlockPos(-1, 1, 0),
                    BlockPos(-1, 1, -2),
                    BlockPos(0, 1, -2),
                    BlockPos(0, 0, -2),
                    BlockPos(1, 0, -2),
                    BlockPos(2, 0, -2),
                    BlockPos(3, 0, -2),
                    BlockPos(4, 0, -2),
                    BlockPos(4, 0, -1),
                    BlockPos(3, 0, -1),
                    BlockPos(2, 0, -1),
                    BlockPos(1, 0, -1),
                    BlockPos(0, 0, -1),
                    BlockPos(0, 0, 0),
                    BlockPos(1, 0, 0),
                    BlockPos(1, 0, 1),
                    BlockPos(0, 0, 1),
                    BlockPos(0, 0, 2),
                    BlockPos(1, 0, 2),
                    BlockPos(2, 0, 2),
                    BlockPos(3, 0, 2),
                    BlockPos(4, 0, 2),
                    BlockPos(4, 0, 1),
                    BlockPos(3, 0, 1),
                    BlockPos(3, 0, 0),
                    BlockPos(4, 0, 0),
                    BlockPos(5, 0, 0),
                )
            ),
            arrayOf(
                arrayOf(
                    BlockPos(-1, 0, 0),
                    BlockPos(-1, 1, 0),
                    BlockPos(-1, 1, -2),
                    BlockPos(0, 1, -2),
                    BlockPos(0, 0, -2),
                    BlockPos(0, 0, -1),
                    BlockPos(0, 0, 0),
                    BlockPos(0, 0, 1),
                    BlockPos(0, 0, 2),
                    BlockPos(0, 0, 3),
                    BlockPos(1, 0, 3),
                    BlockPos(1, 0, 2),
                    BlockPos(1, 0, 1),
                    BlockPos(1, 0, 0),
                    BlockPos(1, 0, -1),
                    BlockPos(1, 0, -2),
                    BlockPos(1, 0, -3),
                    BlockPos(2, 0, -3),
                    BlockPos(2, 0, -2),
                    BlockPos(2, 0, -1),
                    BlockPos(2, 0, 0),
                    BlockPos(2, 0, 1),
                    BlockPos(2, 0, 2),
                    BlockPos(2, 0, 3),
                    BlockPos(3, 0, 3),
                    BlockPos(4, 0, 3),
                    BlockPos(5, 0, 3),
                    BlockPos(6, 0, 3),
                    BlockPos(6, 0, 2),
                    BlockPos(5, 0, 2),
                    BlockPos(4, 0, 2),
                    BlockPos(3, 0, 2),
                    BlockPos(3, 0, 1),
                    BlockPos(3, 0, 0),
                    BlockPos(3, 0, -1),
                    BlockPos(3, 0, -2),
                    BlockPos(3, 0, -3),
                    BlockPos(4, 0, -3),
                    BlockPos(5, 0, -3),
                    BlockPos(6, 0, -3),
                    BlockPos(6, 0, -2),
                    BlockPos(5, 0, -2),
                    BlockPos(4, 0, -2),
                    BlockPos(4, 0, -1),
                    BlockPos(5, 0, -1),
                    BlockPos(5, 0, 0),
                    BlockPos(5, 0, 1),
                    BlockPos(6, 0, 1),
                    BlockPos(6, 0, 0),
                    BlockPos(7, 0, 0),
                ),
                arrayOf(
                    BlockPos(0, 0, 0),
                    BlockPos(0, 0, -1),
                    BlockPos(0, 0, -2),
                    BlockPos(0, 0, -3),
                    BlockPos(1, 0, -3),
                    BlockPos(2, 0, -3),
                    BlockPos(3, 0, -3),
                    BlockPos(4, 0, -3),
                    BlockPos(5, 0, -3),
                    BlockPos(6, 0, -3),
                    BlockPos(6, 0, -2),
                    BlockPos(5, 0, -2),
                    BlockPos(4, 0, -2),
                    BlockPos(3, 0, -2),
                    BlockPos(2, 0, -2),
                    BlockPos(1, 0, -2),
                    BlockPos(1, 0, -1),
                    BlockPos(1, 0, 0),
                    BlockPos(1, 0, 1),
                    BlockPos(0, 0, 1),
                    BlockPos(0, 0, 2),
                    BlockPos(0, 0, 3),
                    BlockPos(1, 0, 3),
                    BlockPos(1, 0, 2),
                    BlockPos(2, 0, 2),
                    BlockPos(2, 0, 3),
                    BlockPos(3, 0, 3),
                    BlockPos(4, 0, 3),
                    BlockPos(5, 0, 3),
                    BlockPos(6, 0, 3),
                    BlockPos(6, 0, 2),
                    BlockPos(5, 0, 2),
                    BlockPos(4, 0, 2),
                    BlockPos(3, 0, 2),
                    BlockPos(3, 0, 1),
                    BlockPos(3, 0, 0),
                    BlockPos(3, 0, -1),
                    BlockPos(4, 0, -1),
                    BlockPos(4, 0, 0),
                    BlockPos(4, 0, 1),
                    BlockPos(5, 0, 1),
                    BlockPos(5, 0, 0),
                    BlockPos(6, 0, 0),
                    BlockPos(7, 0, 0),
                ),
                arrayOf(
                    BlockPos(-1, 0, 0),
                    BlockPos(-1, 1, 0),
                    BlockPos(-1, 1, -4),
                    BlockPos(7, 1, -4),
                    BlockPos(7, 1, -2),
                    BlockPos(6, 1, -2),
                    BlockPos(6, 0, -2),
                    BlockPos(6, 0, -3),
                    BlockPos(5, 0, -3),
                    BlockPos(4, 0, -3),
                    BlockPos(3, 0, -3),
                    BlockPos(2, 0, -3),
                    BlockPos(1, 0, -3),
                    BlockPos(0, 0, -3),
                    BlockPos(0, 0, -2),
                    BlockPos(1, 0, -2),
                    BlockPos(2, 0, -2),
                    BlockPos(3, 0, -2),
                    BlockPos(4, 0, -2),
                    BlockPos(5, 0, -2),
                    BlockPos(5, 0, -1),
                    BlockPos(4, 0, -1),
                    BlockPos(3, 0, -1),
                    BlockPos(3, 0, 0),
                    BlockPos(2, 0, 0),
                    BlockPos(2, 0, -1),
                    BlockPos(1, 0, -1),
                    BlockPos(0, 0, -1),
                    BlockPos(0, 0, 0),
                    BlockPos(0, 0, 1),
                    BlockPos(1, 0, 1),
                    BlockPos(1, 0, 2),
                    BlockPos(0, 0, 2),
                    BlockPos(0, 0, 3),
                    BlockPos(1, 0, 3),
                    BlockPos(2, 0, 3),
                    BlockPos(3, 0, 3),
                    BlockPos(3, 0, 2),
                    BlockPos(3, 0, 1),
                    BlockPos(4, 0, 1),
                    BlockPos(4, 0, 2),
                    BlockPos(4, 0, 3),
                    BlockPos(5, 0, 3),
                    BlockPos(5, 0, 2),
                    BlockPos(6, 0, 2),
                    BlockPos(6, 0, 1),
                    BlockPos(5, 0, 1),
                    BlockPos(5, 0, 0),
                    BlockPos(6, 0, 0),
                    BlockPos(7, 0, 0),
                ),
                arrayOf(
                    BlockPos(0, 0, 0),
                    BlockPos(1, 0, 0),
                    BlockPos(1, 0, -1),
                    BlockPos(0, 0, -1),
                    BlockPos(0, 0, -2),
                    BlockPos(0, 0, -3),
                    BlockPos(1, 0, -3),
                    BlockPos(1, 0, -2),
                    BlockPos(2, 0, -2),
                    BlockPos(2, 0, -3),
                    BlockPos(3, 0, -3),
                    BlockPos(4, 0, -3),
                    BlockPos(5, 0, -3),
                    BlockPos(6, 0, -3),
                    BlockPos(6, 0, -2),
                    BlockPos(5, 0, -2),
                    BlockPos(4, 0, -2),
                    BlockPos(4, 0, -1),
                    BlockPos(5, 0, -1),
                    BlockPos(5, 0, 0),
                    BlockPos(4, 0, 0),
                    BlockPos(3, 0, 0),
                    BlockPos(2, 0, 0),
                    BlockPos(2, 0, 1),
                    BlockPos(3, 0, 1),
                    BlockPos(4, 0, 1),
                    BlockPos(4, 0, 2),
                    BlockPos(3, 0, 2),
                    BlockPos(2, 0, 2),
                    BlockPos(1, 0, 2),
                    BlockPos(0, 0, 2),
                    BlockPos(0, 0, 3),
                    BlockPos(1, 0, 3),
                    BlockPos(2, 0, 3),
                    BlockPos(3, 0, 3),
                    BlockPos(4, 0, 3),
                    BlockPos(5, 0, 3),
                    BlockPos(6, 0, 3),
                    BlockPos(6, 0, 2),
                    BlockPos(6, 0, 1),
                    BlockPos(6, 0, 0),
                    BlockPos(7, 0, 0),
                ),
                arrayOf(
                    BlockPos(0, 0, 0),
                    BlockPos(0, 0, -1),
                    BlockPos(0, 0, -2),
                    BlockPos(0, 0, -3),
                    BlockPos(1, 0, -3),
                    BlockPos(1, 0, -2),
                    BlockPos(1, 0, -1),
                    BlockPos(2, 0, -1),
                    BlockPos(2, 0, -2),
                    BlockPos(2, 0, -3),
                    BlockPos(3, 0, -3),
                    BlockPos(4, 0, -3),
                    BlockPos(5, 0, -3),
                    BlockPos(6, 0, -3),
                    BlockPos(6, 0, -2),
                    BlockPos(5, 0, -2),
                    BlockPos(4, 0, -2),
                    BlockPos(4, 0, -1),
                    BlockPos(5, 0, -1),
                    BlockPos(5, 0, 0),
                    BlockPos(5, 0, 1),
                    BlockPos(4, 0, 1),
                    BlockPos(4, 0, 2),
                    BlockPos(3, 0, 2),
                    BlockPos(2, 0, 2),
                    BlockPos(2, 0, 1),
                    BlockPos(1, 0, 1),
                    BlockPos(0, 0, 1),
                    BlockPos(0, 0, 2),
                    BlockPos(0, 0, 3),
                    BlockPos(1, 0, 3),
                    BlockPos(2, 0, 3),
                    BlockPos(3, 0, 3),
                    BlockPos(4, 0, 3),
                    BlockPos(5, 0, 3),
                    BlockPos(5, 0, 2),
                    BlockPos(6, 0, 2),
                    BlockPos(6, 0, 1),
                    BlockPos(6, 0, 0),
                    BlockPos(7, 0, 0),
                )
            )
        )


    val identifier = listOf(
        listOf(
            Pair(BlockPos(0, 0, -1), BlockPos(2, 0, -1)),
            Pair(BlockPos(0, 0, 1), BlockPos(2, 0, 1)),
            Pair(BlockPos(2, 0, 1), BlockPos(0, 0, 1)),
            Pair(BlockPos(2, 0, -1), BlockPos(0, 0, -1))
        ),
        listOf(
            Pair(BlockPos(1, 0, 0), BlockPos(1, 0, -1)),
            Pair(BlockPos(2, 0, 1), BlockPos(2, 0, 0)),
            Pair(BlockPos(2, 0, 1), BlockPos(1, 0, -1)),
            Pair(BlockPos(0, 0, -2), BlockPos(1, 0, 0)),
            Pair(BlockPos(3, 0, 0), BlockPos(0, 0, -2)),
            Pair(BlockPos(2, 0, -1), BlockPos(2, 0, 0))
        ),
        listOf(
            Pair(BlockPos(4, 0, 2), BlockPos(4, 0, 1)),
            Pair(BlockPos(3, 0, -1), BlockPos(2, 0, -1)),
            Pair(BlockPos(2, 0, 3), BlockPos(2, 0, 2)),
            Pair(BlockPos(3, 0, 0), BlockPos(3, 0, -1)),
            Pair(BlockPos(3, 0, 2), BlockPos(3, 0, 1))
        )
    )

    fun toJson(): String {
        val gson = GsonBuilder()
            .setPrettyPrinting()
            .create()

        fun inverseTransform(x: Int, z: Int): BlockPos = BlockPos(-z, 0, x)

        val identifierJson = identifier.mapIndexed { floorIndex, patternList ->
            patternList.map { pair ->
                listOf(
                    inverseTransform(pair.first.x, pair.first.z),
                    inverseTransform(pair.second.x, pair.second.z)
                ).map { pos ->
                    mapOf(
                        "x" to pos.x + 15,
                        "y" to 70 + floorIndex,
                        "z" to pos.z + if (floorIndex == 0) 7 else if (floorIndex == 1) 12 else 19
                    )
                }
            }
        }

        fun convertBlockPosArray(arr: Array<Array<Array<BlockPos>>>): List<List<List<Map<String, Int>>>> {
            return arr.mapIndexed { index, patterns ->
                patterns.map { pattern ->
                    pattern.map { vec ->
                        val pos = inverseTransform(vec.x, vec.z)
                        mapOf(
                            "x" to pos.x + 15,
                            "y" to 70 + index,
                            "z" to pos.z + if (index == 0) 7 else if (index == 1) 12 else 19
                        )
                    }
                }
            }
        }

        val data = mapOf(
            "identifier" to identifierJson,
            "easy" to convertBlockPosArray(IceFillFloors),
            "hard" to convertBlockPosArray(advanced)
        )

        return gson.toJson(data)
    }
}